[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false
showErrorDetails = true

[global]
developmentMode = false
logLevel = "info"

[client]
caching = true
displayEnabled = true
showErrorDetails = true